import { css } from "@styled-system/css";

const focusRing = {
  boxShadow: "0 0 0 3px rgba(28, 28, 28, 0.18)",
  outline: "none",
};

export const styles = {
  page: css({
    background: "#fbfaf7",
    color: "#202020",
    minH: "100svh",
    px: { base: "4", md: "8" },
    pt: { base: "4", md: "8" },
  }),
  shell: css({
    display: "grid",
    gap: "4",
    maxW: "31rem",
    mx: "auto",
    width: "100%",
  }),
  appHeader: css({
    alignItems: "center",
    borderBottom: "1px solid #dedbd4",
    display: "flex",
    justifyContent: "space-between",
    mb: "2",
    mx: { base: "-4", md: "0" },
    pb: "4",
    px: { base: "4", md: "0" },
  }),
  brand: css({
    alignItems: "center",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    minW: "0",
  }),
  brandMark: css({
    alignItems: "center",
    border: "2px solid #343434",
    borderRadius: "8px",
    color: "#202020",
    display: "inline-flex",
    h: "3rem",
    justifyContent: "center",
    w: "3rem",
  }),
  brandIcon: css({
    h: "1.65rem",
    w: "1.65rem",
  }),
  appTitle: css({
    color: "#5a5a5a",
    fontSize: { base: "1rem", sm: "1.2rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.05",
    m: "0",
    maxW: "100%",
    minW: "0",
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  }),
  setupPanel: css({
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    display: "grid",
    gap: "5",
    p: { base: "4", sm: "5" },
  }),
  submit: css({
    alignItems: "center",
    appearance: "none",
    background: "#202020",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "1rem",
    fontWeight: "800",
    justifyContent: "center",
    letterSpacing: "0",
    lineHeight: "1.2",
    minH: "3.25rem",
    px: "5",
    transition: "background 120ms ease, border-color 120ms ease, box-shadow 120ms ease",
    width: "100%",
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.45",
    },
    _focusVisible: focusRing,
    _hover: {
      background: "#3a3a3a",
      borderColor: "#3a3a3a",
    },
  }),
};
