import { css } from "@styled-system/css";

export const styles = {
  roundSummary: css({
    alignItems: { base: "start", sm: "center" },
    background: "#202020",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    display: "grid",
    gap: { base: "4", sm: "5" },
    gridTemplateColumns: {
      base: "1fr",
      sm: "minmax(0, 1fr) auto minmax(9rem, 0.68fr)",
    },
    p: { base: "4", sm: "5" },
  }),
  roundSummaryText: css({
    alignItems: "center",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    justifySelf: "start",
    minW: "0",
  }),
  cardsIcon: css({
    color: "#f4f1e8",
    h: "2rem",
    w: "2rem",
  }),
  statusLabel: css({
    color: "#d7d2c8",
    fontSize: "0.78rem",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    m: "0 0 2",
    textTransform: "uppercase",
  }),
  roundTitle: css({
    color: "#ffffff",
    fontSize: { base: "1.9rem", sm: "2.25rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    m: "0",
    overflowWrap: "anywhere",
  }),
  roundMeta: css({
    color: "#eee9de",
    fontSize: { base: "1rem", sm: "1.1rem" },
    fontWeight: "700",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "2 0 0",
    whiteSpace: "nowrap",
  }),
  summaryDivider: css({
    background: "rgba(255, 255, 255, 0.34)",
    h: { base: "2px", sm: "4rem" },
    w: { base: "100%", sm: "2px" },
  }),
  leaderSummary: css({
    alignItems: "center",
    display: "grid",
    gap: { base: "2", sm: "3" },
    gridTemplateColumns: "auto minmax(0, 1fr)",
    minW: "0",
  }),
  trophyIcon: css({
    color: "#f6d365",
    h: { base: "2.1rem", sm: "2.45rem" },
    w: { base: "2.1rem", sm: "2.45rem" },
  }),
  leaderLabel: css({
    color: "#f4f1e8",
    fontSize: { base: "0.9rem", sm: "1rem" },
    fontWeight: "800",
    lineHeight: "1.2",
    m: "0",
  }),
  leaderName: css({
    color: "#ffffff",
    fontSize: { base: "1.2rem", sm: "1.35rem" },
    fontWeight: "800",
    lineHeight: "1.2",
    m: "1 0 0",
    overflowWrap: "anywhere",
  }),
};
