import { css } from "@styled-system/css";

const focusRing = {
  boxShadow: "0 0 0 3px rgba(28, 28, 28, 0.18)",
  outline: "none",
};

export const styles = {
  modalBackdrop: css({
    alignItems: { base: "end", sm: "center" },
    background: "rgba(32, 32, 32, 0.56)",
    backdropFilter: "blur(6px)",
    display: "grid",
    inset: "0",
    justifyItems: "center",
    p: { base: "4", sm: "6" },
    position: "fixed",
    zIndex: "20",
  }),
  roundFormPanel: css({
    background: "#ffffff",
    border: "2px solid #4d4d4d",
    borderRadius: "8px",
    boxShadow: "0 1.5rem 4rem rgba(0, 0, 0, 0.28)",
    display: "grid",
    gap: "4",
    maxH: "calc(100svh - 2rem)",
    maxW: "31rem",
    overflowY: "auto",
    p: "4",
    width: "100%",
  }),
  roundFormHeader: css({
    alignItems: "start",
    display: "flex",
    gap: "3",
    justifyContent: "space-between",
  }),
  sectionTitle: css({
    fontSize: "1.2rem",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "0",
  }),
  roundMeta: css({
    color: "#3e3e3e",
    fontSize: { base: "1.1rem", sm: "1.25rem" },
    fontWeight: "700",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "2 0 0",
  }),
  closeButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: "0",
    h: "2.75rem",
    justifyContent: "center",
    w: "2.75rem",
    _focusVisible: focusRing,
    _hover: {
      background: "#f0eee8",
    },
  }),
  closeIcon: css({
    h: "1.4rem",
    w: "1.4rem",
  }),
  roundForm: css({
    display: "grid",
    gap: "3",
  }),
  helpText: css({
    color: "#5a5a5a",
    fontSize: "0.9rem",
    lineHeight: "1.4",
    m: "0",
  }),
  scoreField: css({
    alignItems: "center",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "minmax(0, 1fr) 9.75rem",
  }),
  scoreLabel: css({
    alignItems: "center",
    color: "#202020",
    display: "flex",
    fontSize: "1rem",
    fontWeight: "800",
    gap: "2",
    justifyContent: "space-between",
    lineHeight: "1.2",
    minW: "0",
    "& span:first-of-type": {
      overflowWrap: "anywhere",
    },
    "& span:last-of-type": {
      color: "#6a6a6a",
      flexShrink: "0",
      fontSize: "0.8rem",
      textTransform: "uppercase",
    },
  }),
  scoreControl: css({
    display: "grid",
    gap: "2",
    gridTemplateColumns: "3rem minmax(0, 1fr)",
  }),
  signToggleButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.9rem",
    fontWeight: "800",
    justifyContent: "center",
    lineHeight: "1",
    minH: "3.25rem",
    px: "2",
    _focusVisible: focusRing,
    _hover: {
      background: "#f0eee8",
    },
    "&[aria-pressed=true]": {
      background: "#202020",
      borderColor: "#202020",
      color: "#ffffff",
    },
  }),
  scoreInput: css({
    appearance: "none",
    background: "#fbfaf7",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    fontSize: "1.2rem",
    fontWeight: "800",
    lineHeight: "1.2",
    minH: "3.25rem",
    outline: "none",
    px: "3",
    textAlign: "right",
    width: "100%",
    _focusVisible: focusRing,
  }),
  error: css({
    color: "#9f1239",
    fontSize: "0.9375rem",
    fontWeight: "800",
    lineHeight: "1.4",
    m: "0",
  }),
  roundFormActions: css({
    display: "grid",
    gap: "2",
    gridTemplateColumns: "1fr 1fr",
    mt: "1",
  }),
  cancelButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "1rem",
    fontWeight: "800",
    justifyContent: "center",
    minH: "3rem",
    px: "4",
    _focusVisible: focusRing,
  }),
  saveButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#202020",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "1rem",
    fontWeight: "800",
    justifyContent: "center",
    minH: "3rem",
    px: "4",
    _focusVisible: focusRing,
  }),
};
