import { css } from "@styled-system/css";

const focusRing = {
  boxShadow: "0 0 0 3px rgba(28, 28, 28, 0.18)",
  outline: "none",
};

export const styles = {
  roundFormPanel: css({
    background: "#ffffff",
    border: "2px solid #4d4d4d",
    borderRadius: "8px",
    display: "grid",
    gap: "4",
    p: "4",
  }),
  roundFormHeader: css({
    alignItems: "start",
    display: "flex",
    justifyContent: "space-between",
  }),
  sectionTitle: css({
    fontSize: "1.2rem",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "0",
  }),
  roundMeta: css({
    color: "#3e3e3e",
    fontSize: { base: "1.1rem", sm: "1.25rem" },
    fontWeight: "700",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "2 0 0",
  }),
  roundForm: css({
    display: "grid",
    gap: "3",
  }),
  helpText: css({
    color: "#5a5a5a",
    fontSize: "0.9rem",
    lineHeight: "1.4",
    m: "0",
  }),
  scoreField: css({
    alignItems: "center",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "minmax(0, 1fr) 7rem",
  }),
  scoreLabel: css({
    alignItems: "center",
    color: "#202020",
    display: "flex",
    fontSize: "1rem",
    fontWeight: "800",
    gap: "2",
    justifyContent: "space-between",
    lineHeight: "1.2",
    minW: "0",
    "& span:first-of-type": {
      overflowWrap: "anywhere",
    },
    "& span:last-of-type": {
      color: "#6a6a6a",
      flexShrink: "0",
      fontSize: "0.8rem",
      textTransform: "uppercase",
    },
  }),
  scoreInput: css({
    appearance: "none",
    background: "#fbfaf7",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    fontSize: "1.2rem",
    fontWeight: "800",
    lineHeight: "1.2",
    minH: "3.25rem",
    outline: "none",
    px: "3",
    textAlign: "right",
    width: "100%",
    _focusVisible: focusRing,
  }),
  error: css({
    color: "#9f1239",
    fontSize: "0.9375rem",
    fontWeight: "800",
    lineHeight: "1.4",
    m: "0",
  }),
  roundFormActions: css({
    display: "grid",
    gap: "2",
    gridTemplateColumns: "1fr 1fr",
    mt: "1",
  }),
  cancelButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "1rem",
    fontWeight: "800",
    justifyContent: "center",
    minH: "3rem",
    px: "4",
    _focusVisible: focusRing,
  }),
  saveButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#202020",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "1rem",
    fontWeight: "800",
    justifyContent: "center",
    minH: "3rem",
    px: "4",
    _focusVisible: focusRing,
  }),
};
