import { css } from "@styled-system/css";

const focusRing = {
  boxShadow: "0 0 0 3px rgba(28, 28, 28, 0.18)",
  outline: "none",
};

export const styles = {
  page: css({
    background: "#fbfaf7",
    color: "#202020",
    minH: "100svh",
    pb: "calc(7rem + env(safe-area-inset-bottom))",
    px: { base: "4", md: "8" },
    pt: { base: "4", md: "8" },
  }),
  shell: css({
    display: "grid",
    gap: "4",
    maxW: "31rem",
    mx: "auto",
    width: "100%",
  }),
  appHeader: css({
    alignItems: "center",
    borderBottom: "1px solid #dedbd4",
    display: "flex",
    justifyContent: "space-between",
    mb: "2",
    mx: { base: "-4", md: "0" },
    pb: "4",
    px: { base: "4", md: "0" },
  }),
  appTitle: css({
    color: "#202020",
    fontSize: { base: "2.05rem", md: "2.35rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    m: "0",
  }),
  iconButton: css({
    alignItems: "center",
    background: "#ffffff",
    border: "2px solid #343434",
    borderRadius: "8px",
    color: "#202020",
    display: "inline-flex",
    h: "3.35rem",
    justifyContent: "center",
    textDecoration: "none",
    transition: "background 120ms ease, box-shadow 120ms ease",
    w: "3.35rem",
    _focusVisible: focusRing,
    _hover: {
      background: "#f0eee8",
    },
  }),
  headerIcon: css({
    h: "1.8rem",
    w: "1.8rem",
  }),
  form: css({
    display: "grid",
    gap: "2",
  }),
  label: css({
    color: "#4d4d4d",
    fontSize: "0.9rem",
    fontWeight: "800",
    lineHeight: "1.2",
  }),
  inputRow: css({
    display: "grid",
    gap: "2",
    gridTemplateColumns: "minmax(0, 1fr) auto",
  }),
  input: css({
    appearance: "none",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    fontSize: "1rem",
    lineHeight: "1.4",
    minH: "3.25rem",
    outline: "none",
    px: "3",
    width: "100%",
    _focusVisible: focusRing,
    _placeholder: {
      color: "#767676",
    },
  }),
  submitButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#202020",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "0.95rem",
    fontWeight: "800",
    justifyContent: "center",
    minH: "3.25rem",
    minW: "5.75rem",
    px: "4",
    _disabled: {
      cursor: "wait",
      opacity: "0.65",
    },
    _focusVisible: focusRing,
    _hover: {
      background: "#3a3a3a",
      borderColor: "#3a3a3a",
    },
  }),
  error: css({
    color: "#9f1239",
    fontSize: "0.9375rem",
    fontWeight: "800",
    lineHeight: "1.4",
    m: "0",
  }),
  result: css({
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    color: "#202020",
    display: "grid",
    gap: "4",
    m: "0",
    p: "4",
  }),
  resultText: css({
    fontSize: "1.2rem",
    fontWeight: "800",
    lineHeight: "1.3",
    m: "0",
  }),
  definitions: css({
    borderTop: "1px solid #dedbd4",
    display: "grid",
    gap: "3",
    pt: "4",
  }),
  definitionsTitle: css({
    color: "#4d4d4d",
    fontSize: "0.9rem",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "0",
    textTransform: "uppercase",
  }),
  definitionList: css({
    display: "grid",
    gap: "3",
    listStyle: "none",
    m: "0",
    p: "0",
  }),
  definitionItem: css({
    display: "grid",
    gap: "1",
  }),
  partOfSpeech: css({
    color: "#5a5a5a",
    fontSize: "0.85rem",
    fontStyle: "italic",
    fontWeight: "800",
    lineHeight: "1.2",
    m: "0",
  }),
  definitionText: css({
    color: "#202020",
    fontSize: "1rem",
    fontWeight: "700",
    lineHeight: "1.45",
    m: "0",
  }),
  example: css({
    color: "#5a5a5a",
    fontSize: "0.92rem",
    lineHeight: "1.4",
    m: "0",
    "& span": {
      fontWeight: "800",
    },
  }),
};
