import { css } from "@styled-system/css";

export const styles = {
  standingsSection: css({
    display: "grid",
    gap: "2",
  }),
  sectionHeader: css({
    alignItems: "end",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    px: "1",
  }),
  sectionTitle: css({
    color: "#202020",
    fontSize: "1.05rem",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.2",
    m: "0",
  }),
  sectionMeta: css({
    color: "#6a6a6a",
    fontSize: "0.78rem",
    fontWeight: "800",
    lineHeight: "1.2",
    textTransform: "uppercase",
  }),
  emptyState: css({
    background: "#ffffff",
    border: "2px dashed #b8b6b0",
    borderRadius: "8px",
    display: "grid",
    gap: "2",
    p: "5",
  }),
  emptyTitle: css({
    fontSize: "1.05rem",
    fontWeight: "800",
    lineHeight: "1.3",
    m: "0",
  }),
  emptyBody: css({
    color: "#5a5a5a",
    fontSize: "0.95rem",
    lineHeight: "1.45",
    m: "0",
  }),
  playerList: css({
    display: "grid",
    gap: "2",
    listStyle: "none",
    m: "0",
    p: "0",
  }),
  playerCard: css({
    alignItems: "center",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    display: "grid",
    gap: "3",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    minH: "4.25rem",
    p: "3",
  }),
  playerCardLeader: css({
    background: "#f6f4ef",
    borderColor: "#4d4d4d",
  }),
  playerCardWinner: css({
    background: "#e8f7ec",
    borderColor: "#15803d",
    boxShadow: "0 0.45rem 1.25rem rgba(21, 128, 61, 0.14)",
  }),
  playerRank: css({
    alignItems: "center",
    background: "#f6f4ef",
    border: "2px solid #d7d4cc",
    borderRadius: "999px",
    color: "#4d4d4d",
    display: "inline-flex",
    fontSize: "0.95rem",
    fontWeight: "800",
    h: "2.4rem",
    justifyContent: "center",
    lineHeight: "1",
    w: "2.4rem",
  }),
  playerNameGroup: css({
    alignItems: "start",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    gap: "1",
    minW: "0",
  }),
  playerName: css({
    fontSize: { base: "1.18rem", sm: "1.3rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1.15",
    minW: "0",
    overflowWrap: "anywhere",
  }),
  playerNameWinner: css({
    background: "#bbf7d0",
    borderRadius: "999px",
    color: "#14532d",
    px: "2",
    py: "1",
  }),
  leaderBadge: css({
    alignItems: "center",
    color: "#3a3a3a",
    display: "inline-flex",
    fontSize: "0.72rem",
    fontWeight: "800",
    gap: "1",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  winnerBadge: css({
    color: "#14532d",
  }),
  leaderBadgeIcon: css({
    h: "1.1rem",
    w: "1.1rem",
  }),
  totalScore: css({
    fontSize: { base: "1.85rem", sm: "2rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
  }),
  totalScoreHighlight: css({
    fontSize: { base: "2.15rem", sm: "2.35rem" },
  }),
  totalScoreWinner: css({
    color: "#14532d",
  }),
};
