import { css } from "@styled-system/css";

export const styles = {
  standingsSection: css({
    display: "grid",
    gap: "3",
  }),
  visuallyHidden: css({
    border: "0",
    clip: "rect(0 0 0 0)",
    h: "1px",
    m: "-1px",
    overflow: "hidden",
    p: "0",
    position: "absolute",
    whiteSpace: "nowrap",
    w: "1px",
  }),
  emptyState: css({
    background: "#ffffff",
    border: "2px dashed #b8b6b0",
    borderRadius: "8px",
    display: "grid",
    gap: "2",
    p: "5",
  }),
  emptyTitle: css({
    fontSize: "1.05rem",
    fontWeight: "800",
    lineHeight: "1.3",
    m: "0",
  }),
  emptyBody: css({
    color: "#5a5a5a",
    fontSize: "0.95rem",
    lineHeight: "1.45",
    m: "0",
  }),
  playerList: css({
    display: "grid",
    gap: "3",
    listStyle: "none",
    m: "0",
    p: "0",
  }),
  playerCard: css({
    alignItems: "center",
    background: "#ffffff",
    border: "2px solid #c9c7c1",
    borderRadius: "8px",
    display: "grid",
    gap: "4",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    minH: "5.25rem",
    p: { base: "3", sm: "4" },
  }),
  playerCardLeader: css({
    background: "#f6f4ef",
    borderColor: "#4d4d4d",
  }),
  avatar: css({
    alignItems: "center",
    border: "2px solid #b8b6b0",
    borderRadius: "999px",
    color: "#a5a19a",
    display: "inline-flex",
    h: { base: "3rem", sm: "3.4rem" },
    justifyContent: "center",
    w: { base: "3rem", sm: "3.4rem" },
  }),
  avatarIcon: css({
    h: "2rem",
    w: "2rem",
  }),
  playerNameGroup: css({
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "2",
    minW: "0",
  }),
  playerName: css({
    fontSize: { base: "1.85rem", sm: "2.1rem" },
    fontWeight: "750",
    letterSpacing: "0",
    lineHeight: "1.1",
    minW: "0",
    overflowWrap: "anywhere",
  }),
  leaderBadge: css({
    alignItems: "center",
    color: "#3a3a3a",
    display: "inline-flex",
    fontSize: "0.72rem",
    fontWeight: "800",
    gap: "1",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  leaderBadgeIcon: css({
    h: "1.45rem",
    w: "1.45rem",
  }),
  totalScore: css({
    fontSize: { base: "2.45rem", sm: "2.8rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
  }),
};
