import { css } from "@styled-system/css";

const focusRing = {
  boxShadow: "0 0 0 3px rgba(28, 28, 28, 0.18)",
  outline: "none",
};

export const styles = {
  page: css({
    background: "#fbfaf7",
    color: "#202020",
    minH: "100svh",
    pb: "calc(7rem + env(safe-area-inset-bottom))",
    px: { base: "4", md: "8" },
    pt: { base: "4", md: "8" },
  }),
  shell: css({
    display: "grid",
    gap: "4",
    maxW: "31rem",
    mx: "auto",
    width: "100%",
  }),
  appHeader: css({
    alignItems: "center",
    borderBottom: "1px solid #dedbd4",
    display: "flex",
    justifyContent: "space-between",
    mb: "2",
    mx: { base: "-4", md: "0" },
    pb: "4",
    px: { base: "4", md: "0" },
  }),
  appTitle: css({
    color: "#202020",
    fontSize: { base: "2.35rem", md: "2.7rem" },
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    m: "0",
  }),
  iconButton: css({
    alignItems: "center",
    background: "#ffffff",
    border: "2px solid #343434",
    borderRadius: "8px",
    color: "#202020",
    display: "inline-flex",
    h: "3.35rem",
    justifyContent: "center",
    textDecoration: "none",
    transition: "background 120ms ease, box-shadow 120ms ease",
    w: "3.35rem",
    _focusVisible: focusRing,
    _hover: {
      background: "#f0eee8",
    },
  }),
  headerIcon: css({
    h: "1.8rem",
    w: "1.8rem",
  }),
  addRoundButton: css({
    alignItems: "center",
    appearance: "none",
    background: "#6b6b6b",
    border: "2px solid #202020",
    borderRadius: "8px",
    color: "#ffffff",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: { base: "2rem", sm: "2.3rem" },
    fontWeight: "800",
    gap: "4",
    justifyContent: "center",
    letterSpacing: "0",
    lineHeight: "1",
    minH: "5.25rem",
    px: "5",
    textShadow: "0 1px 1px rgba(0, 0, 0, 0.25)",
    width: "100%",
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.45",
    },
    _focusVisible: focusRing,
    _hover: {
      background: "#555555",
    },
  }),
  addRoundIcon: css({
    h: "2.3rem",
    w: "2.3rem",
  }),
  newGameButton: css({
    appearance: "none",
    background: "transparent",
    border: "0",
    color: "#5a5a5a",
    cursor: "pointer",
    fontSize: "0.95rem",
    fontWeight: "800",
    justifySelf: "center",
    letterSpacing: "0",
    lineHeight: "1.2",
    mt: "1",
    p: "2",
    textDecoration: "underline",
    textUnderlineOffset: "0.2em",
    _focusVisible: focusRing,
  }),
};
